---
stages:
  - build
  - test
  - quality

variables:
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp, dist"
  SECURE_LOG_LEVEL: "debug"
  SAST_DISABLE_BABEL: "true"

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

build_app:
  image: vuejs/ci
  stage: build
  script:
    - yarn global add @vue/cli
    - yarn global add @vue/cli-service-global
    - yarn install --production=false
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit_tests:
  image: vuejs/ci
  stage: test
  script:
    - yarn global add @vue/cli
    - yarn global add @vue/cli-service-global
    - yarn install --production=false
    - yarn test:unit --coverage --reporters="default" --reporters="jest-junit"
  artifacts:
    paths:
      - "junit.xml"
      - "coverage/clover"
    reports:
      junit: junit.xml

#e2e_tests:
#  image: ebiven/vue-cli
#  stage: test
#  script:
#    - yarn install --progress=false
#    - vue-cli-service test:e2e

sonar:
  image: sonarsource/sonar-scanner-cli:latest
  stage: quality
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.login="${SONAR_CLOUD_LOGIN}" -X
  allow_failure: true
  variables:
    SONAR_PROJECT_BASE_DIR: "${CI_PROJECT_DIR}"
    SONAR_TOKEN: "${SONAR_CLOUD_LOGIN}"
    SONAR_LOGIN: "${SONAR_CLOUD_LOGIN}"
    SONAR_HOST_URL: https://sonarcloud.io
    GIT_DEPTH: 0
  only:
    - master
